local generated_path = arg and arg[1]
if not generated_path then
    error("Usage: lua tests/test-lua-embed-file.lua <generated.lua>")
end

local generated = dofile(generated_path)
assert(generated.script == [[
[ENABLE]
define(exampleValue, 42)

[DISABLE]
unregisterSymbol(exampleValue)
]], "embedded script did not match the source file")
assert(generated.notes == "Generated by lua-embed-file.\n", "embedded notes did not match the source file")

print("lua-embed-file packaged CLI test passed")
