local compiler = {}

local function location_error(source, source_name)
    local chunk, syntax_error = load(source, "@" .. source_name, "t", {})
    if chunk == nil then
        return syntax_error
    end
end

---@param args { source: string, source_name?: string, runtime_source: string }
---@return string
function compiler.compile(args)
    assert(type(args) == "table", "compile expects an argument table")
    assert(type(args.source) == "string", "source must be a string")
    assert(type(args.runtime_source) == "string", "runtime_source must be a string")
    local source_name = args.source_name or "<input>"

    local source_error = location_error(args.source, source_name)
    if source_error then
        error(source_error, 0)
    end
    local runtime_error = location_error(args.runtime_source, "table_builder_runtime.lua")
    if runtime_error then
        error(runtime_error, 0)
    end

    local generated = table.concat({
        "-- Generated by table-builder. Do not edit.\n",
        "local table_builder = (function()\n",
        args.runtime_source,
        "\nend)()\n",
        "local definition = (function()\n",
        args.source,
        "\nend)()\n",
        "return table_builder.build(definition)\n",
    })
    local generated_error = location_error(generated, "<generated-table-builder-script>")
    if generated_error then
        error(generated_error, 0)
    end
    return generated
end

local function usage()
    return [[Usage: table-builder [-o OUTPUT] [INPUT|-]

Compile a declarative Lua table definition into a standalone Cheat Engine script.
INPUT defaults to stdin. Generated Lua is written to stdout unless -o is supplied.]]
end

local function normalize_path(path)
    local absolute = path:sub(1, 1) == "/"
    local parts = {}
    for part in (path .. "/"):gmatch("(.-)/") do
        if part == ".." and #parts > 0 and parts[#parts] ~= ".." then
            table.remove(parts)
        elseif part ~= "" and part ~= "." then
            parts[#parts + 1] = part
        end
    end
    return (absolute and "/" or "") .. table.concat(parts, "/")
end

local function parse_args(argv)
    local options, positional = {}, {}
    local cursor = 1
    while cursor <= #argv do
        local value = argv[cursor]
        if value == "-h" or value == "--help" then
            options.help = true
        elseif value == "-o" or value == "--output" then
            cursor = cursor + 1
            options.output = argv[cursor]
            if options.output == nil then
                return nil, value .. " requires a file"
            end
        elseif value == "--" then
            for index = cursor + 1, #argv do
                positional[#positional + 1] = argv[index]
            end
            break
        elseif value:sub(1, 1) == "-" and value ~= "-" then
            return nil, "unknown option: " .. value
        else
            positional[#positional + 1] = value
        end
        cursor = cursor + 1
    end
    if options.help then
        return options
    end
    if #positional > 1 then
        return nil, "at most one input file is allowed"
    end
    options.input = positional[1] or "-"
    if options.input ~= "-" and options.output and normalize_path(options.input) == normalize_path(options.output) then
        return nil, "output must not overwrite the input definition"
    end
    return options
end

local function read_stream(stream)
    return stream:read("*a")
end

local function read_file(path)
    local file, open_error = io.open(path, "rb")
    if file == nil then
        return nil, open_error
    end
    local content = file:read("*a")
    local ok, close_error = file:close()
    if not ok then
        return nil, close_error
    end
    return content
end

local function atomic_write(path, content)
    local temporary
    for suffix = 1, 1000 do
        local candidate = path .. ".tmp." .. suffix
        local existing = io.open(candidate, "rb")
        if existing == nil then
            temporary = candidate
            break
        end
        existing:close()
    end
    if temporary == nil then
        return nil, "could not allocate a temporary output file"
    end
    local file, open_error = io.open(temporary, "wb")
    if file == nil then
        return nil, open_error
    end
    local written, write_error = file:write(content)
    if not written then
        file:close()
        os.remove(temporary)
        return nil, write_error
    end
    local closed, close_error = file:close()
    if not closed then
        os.remove(temporary)
        return nil, close_error
    end
    local renamed, rename_error = os.rename(temporary, path)
    if not renamed then
        os.remove(temporary)
        return nil, rename_error
    end
    return true
end

---@param argv string[]
---@param streams? { stdin?: file*, stdout?: file*, stderr?: file* }
---@param environment? { runtime_path?: string }
---@return boolean
function compiler.run(argv, streams, environment)
    streams = streams or {}
    environment = environment or {}
    local stdin = streams.stdin or io.stdin
    local stdout = streams.stdout or io.stdout
    local stderr = streams.stderr or io.stderr
    local options, argument_error = parse_args(argv)
    if options == nil then
        stderr:write("table-builder: " .. argument_error .. "\n\n" .. usage() .. "\n")
        return false
    end
    if options.help then
        stdout:write(usage() .. "\n")
        return true
    end

    local source, source_error
    if options.input == "-" then
        source = read_stream(stdin)
    else
        source, source_error = read_file(options.input)
    end
    if source == nil then
        stderr:write(string.format("table-builder: cannot read %s: %s\n", options.input, source_error or "read failed"))
        return false
    end

    local runtime_path = environment.runtime_path or os.getenv("TABLE_BUILDER_RUNTIME")
    if runtime_path == nil or runtime_path == "" then
        stderr:write("table-builder: TABLE_BUILDER_RUNTIME is not configured\n")
        return false
    end
    local runtime_source, runtime_read_error = read_file(runtime_path)
    if runtime_source == nil then
        stderr:write(string.format("table-builder: cannot read runtime %s: %s\n", runtime_path, runtime_read_error))
        return false
    end

    local ok, generated = pcall(compiler.compile, {
        source = source,
        source_name = options.input == "-" and "<stdin>" or options.input,
        runtime_source = runtime_source,
    })
    if not ok then
        stderr:write("table-builder: " .. generated .. "\n")
        return false
    end
    if options.output == nil then
        stdout:write(generated)
        return true
    end
    local written, write_error = atomic_write(options.output, generated)
    if not written then
        stderr:write(string.format("table-builder: cannot write %s: %s\n", options.output, write_error))
        return false
    end
    return true
end

return compiler
